[2022-09-09 10:01:40,428] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: trip_etl.ssh_task 2022-09-09T10:01:39.615161+00:00 [queued]>
[2022-09-09 10:01:40,435] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: trip_etl.ssh_task 2022-09-09T10:01:39.615161+00:00 [queued]>
[2022-09-09 10:01:40,435] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 10:01:40,436] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2022-09-09 10:01:40,436] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 10:01:40,445] {taskinstance.py:1089} INFO - Executing <Task(SSHOperator): ssh_task> on 2022-09-09T10:01:39.615161+00:00
[2022-09-09 10:01:40,448] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2022-09-09 10:01:40,450] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trip_etl', 'ssh_task', '2022-09-09T10:01:39.615161+00:00', '--job-id', '87', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse test.py', '--cfg-path', '/tmp/tmpq9eue6ng', '--error-file', '/tmp/tmpkkqa_foi']
[2022-09-09 10:01:40,451] {standard_task_runner.py:77} INFO - Job 87: Subtask ssh_task
[2022-09-09 10:01:40,482] {logging_mixin.py:104} INFO - Running <TaskInstance: trip_etl.ssh_task 2022-09-09T10:01:39.615161+00:00 [running]> on host 3f125d5f6fbd
[2022-09-09 10:01:40,510] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trip_etl
AIRFLOW_CTX_TASK_ID=ssh_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-09T10:01:39.615161+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-09T10:01:39.615161+00:00
[2022-09-09 10:01:40,510] {ssh.py:91} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2022-09-09 10:01:40,516] {base.py:78} INFO - Using connection to: id: nfrssh. Host: 172.30.16.1, Port: 22, Schema: , Login: nfrs, Password: XXXXXXXX, extra: XXXXXXXX
[2022-09-09 10:01:40,517] {ssh.py:204} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2022-09-09 10:01:40,517] {ssh.py:210} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2022-09-09 10:01:40,559] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_8.1)
[2022-09-09 10:01:40,657] {transport.py:1819} INFO - Authentication (password) successful!
[2022-09-09 10:01:40,658] {ssh.py:110} INFO - Running command: C:/Users/nfrs/Documents/Jupyter/NetologyDiplom/bin.bat
[2022-09-09 10:01:40,713] {ssh.py:142} INFO - 
nfrs@DESKTOP-FKD5HF9 C:\Users\nfrs>set root=C:\Users\nfrs\anaconda3 

[2022-09-09 10:01:40,713] {ssh.py:142} INFO - nfrs@DESKTOP-FKD5HF9 C:\Users\nfrs>call C:\Users\nfrs\anaconda3\Scripts\activate.bat C:\Users\nfrs\anaconda3 
[2022-09-09 10:01:41,724] {ssh.py:142} INFO - 
[2022-09-09 10:01:41,725] {ssh.py:142} INFO - (base) nfrs@DESKTOP-FKD5HF9 C:\Users\nfrs>call python trip_etl.py 
[2022-09-09 10:01:41,778] {ssh.py:146} WARNING - python: can't open file 'C:\Users\nfrs\trip_etl.py': [Errno 2] No such file or directory
[2022-09-09 10:01:41,783] {ssh.py:142} INFO - 
(base) nfrs@DESKTOP-FKD5HF9 C:\Users\nfrs>pause
Press any key to continue . . . 
[2022-09-09 10:01:41,783] {ssh.py:142} INFO - 
[2022-09-09 10:01:41,802] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=trip_etl, task_id=ssh_task, execution_date=20220909T100139, start_date=20220909T100140, end_date=20220909T100141
[2022-09-09 10:01:41,819] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-09 10:01:41,829] {local_task_job.py:146} INFO - Task exited with return code 0
